apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: elastic-platform
  labels:
    app: otel-collector
    app.kubernetes.io/part-of: elastic-platform
  annotations:
    argocd.argoproj.io/sync-wave: "48"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:0.134.1
          args: ["--config=/etc/otel-collector-config.yml"]
          ports:
            - containerPort: 4317
              name: otlp-grpc
            - containerPort: 4318
              name: otlp-http
          volumeMounts:
            - name: otel-config
              mountPath: /etc/otel-collector-config.yml
              subPath: otel-collector-config.yml
              readOnly: true
      volumes:
        - name: otel-config
          configMap:
            name: otel-collector-config
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: elastic-platform
  labels:
    app: otel-collector
    app.kubernetes.io/part-of: elastic-platform
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  type: ClusterIP
  selector:
    app: otel-collector
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
