apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-data
  namespace: ai-platform
  labels:
    app.kubernetes.io/part-of: ai-platform
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: hf-cache-tei
#   namespace: ai-platform
#   labels:
#     app.kubernetes.io/part-of: ai-platform
#   annotations:
#     argocd.argoproj.io/sync-wave: "20"
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: local-path
#   resources:
#     requests:
#       storage: 7Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: hf-cache-tei-reranker
#   namespace: ai-platform
#   labels:
#     app.kubernetes.io/part-of: ai-platform
#   annotations:
#     argocd.argoproj.io/sync-wave: "20"
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: local-path
#   resources:
#     requests:
#       storage: 7Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: hf-cache-tei-splade
#   namespace: ai-platform
#   labels:
#     app.kubernetes.io/part-of: ai-platform
#   annotations:
#     argocd.argoproj.io/sync-wave: "20"
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: local-path
#   resources:
#     requests:
#       storage: 7Gi
    
#---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: open-webui-data
#   namespace: ai-platform
#   labels:
#     app.kubernetes.io/part-of: ai-platform
#  annotations:
#    argocd.argoproj.io/sync-wave: "20"
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: local-path
#   resources:
#     requests:
#       storage: 5Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: ollama-data
#   namespace: ai-platform
#   labels:
#     app.kubernetes.io/part-of: ai-platform
#  annotations:
#    argocd.argoproj.io/sync-wave: "20"
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: local-path
#   resources:
#     requests:
#       storage: 50Gi