apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-pod-data-pv
spec:
  capacity:
    storage: 15Gi # Request an appropriate size, will still allow the full space available on the host and not limit it to this value
  accessModes:
    - ReadWriteMany # Allows read/write access from multiple nodes/pods
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pod-app-data
  hostPath:
    path: /pods # Must match the path used in k3d create command
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-pod-data-pvc
spec:
  storageClassName: pod-app-data
  accessModes:
    - ReadWriteMany # Request ReadWriteMany access
  resources:
    requests:
      storage: 15Gi # Request an appropriate size, just needs to be less than or equal to the PV but will still allow the full space available on the host and not limit it to this value