apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-data
  namespace: kafka-platform
  labels:
    app.kubernetes.io/part-of: kafka-platform
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-txn
  namespace: kafka-platform
  labels:
    app.kubernetes.io/part-of: kafka-platform
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-data
  namespace: kafka-platform
  labels:
    app.kubernetes.io/part-of: kafka-platform
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
