apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openobserve-data
  namespace: openobserve-platform
  labels:
    app.kubernetes.io/part-of: openobserve-platform
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
